
# Generated by CodiumAI
from currency import exchangeable_value


import pytest

class TestExchangeableValue:

    # Test that the function 'exchangeable_value' returns the correct maximum value when given budget, exchange_rate, spread, and denomination values within the normal range.
    def test_normal_range_values(self):
        assert exchangeable_value(127.25, 1.20, 10, 20) == 106.04166666666667

